import type { Metadata } from "next";
// Google fonts
import { Nunito } from "next/font/google";
// Styles global
import "./assets/styles/index.scss";

const nunito = Nunito({
  subsets: ["cyrillic"],
  weight: ["300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
